### PR TITLE
updates to eslintrc

### PR DESCRIPTION
**Pull request by chrxs**
- separate es6 version

### CODE REVIEW

**Comment by yggie** [comment]
how would you configure a project to use the es6 version? or is this process manual? :grin:

**Comment by cajoy** [comment]
Team,

Can I advise you to move forward into Typescript instead of Babel. There is a lot of benefits in Typescript. And you can compile it to ES6, ES7 or whatever you want without any issues.

**Comment by chrxs** [comment]
@yggie yeah manual for now, you will need to setup the linter for your project
@cajoy I haven't looked in to Typescript yet, it does look good. I think we should be able to use babel or typescript and not limit to a single tool. This update shouldn't be specific to anything so I will remove babel related parts

**Comment by cajoy** [comment]
ok @chrxs,   Just let me know if you need any introduction into Typescript or so. 

I've done couple of small projects using Typescript for Alliants.

**Pull request closed without merging**
